[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IndexedTables = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuliaDB = "a93385a2-3734-596a-9a66-3cfbb77141e6"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Neo4j = "d2adbeaf-5838-5367-8a2f-e46d570981db"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StaticGraphs = "4c8beaf5-199b-59a0-a7f2-21d17de635b6"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TensorDecompositions = "192bee09-7f27-5365-8a12-1b6f807ba546"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
TensorToolbox = "9c690861-8ade-587a-897e-15364bc6f718"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
